Cause:	#[exception.getMessage()]

Flow:	#[exception.event.flowConstruct.name]